services:
  rva-music-scrapers:
    build: .
    environment:
      - ENV=DEV
    volumes:
      - ./service.json:/app/service.json
    depends_on:
      selenium:
        condition: service_healthy
  selenium:
    image: "selenium/standalone-chrome"
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh"]
      interval: 10s
      timeout: 5s
      retries: 3