services:
  rva-music-scrapers:
    build: .
    environment:
      - SELENIUM_HOST=http://selenium:4444/wd/hub
    volumes:
      - ./service.json:/app/service.json
#      - /home/containers/music-calendar/generatedImages:/app/generatedImages/
    depends_on:
      selenium:
        condition: service_healthy

  selenium:
    image: "selenium/standalone-chrome"
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh"]
      interval: 10s
      timeout: 5s
      retries: 3